### ISSUE TITLE
instanceOverrides bug

### ISSUE THREAD

**Issue by agouin** [strangelove-ventures/cosmos-operator#211]
Sequence of events:
- set `disable: Pod` in instance overrides for `pod-0` and applied. `pod-0` Terminated as expected and did not re-schedule.
- Added instanceOverrides for `pod-1` and `pod-2` and removed the `disable: Pod` for `pod-0`. After applying these changes in a single `kubectl apply -k .`, `pod-0` would not schedule. I played around with re-adding `disable: Pod` and removing again, but no luck.
- Removed all instance overrides and applied. This caused `pod-0` to be rescheduled, then I was able to add instance overrides for 1 and 2.

**Comment by DavidNix** [comment]
FYI, this may be a result of managing the CosmosFullNode resource through helm in our infra deployment. It's now pulled out of helm and worth a re-testing.

**Comment by DavidNix** [comment]
Iceboxing because I think this was more related to how we deployed the helm release in our infra.

**Comment by agouin** [comment]
no longer seeing this
