### ISSUE TITLE
Delete the wasm cache if pod is crashlooping 

### ISSUE THREAD

**Issue by DavidNix** [strangelove-ventures/cosmos-operator#300]
This gets into a larger self-healing feature of crashloop mitigation.

See: https://github.com/CosmWasm/wasmvm/issues/426

We could delete the cache on every restart, but I'm unsure how it will affect performance. Per the above, there will be a "slowdown".

**Comment by webmaster128** [comment]
> We could delete the cache on every restart, but I'm unsure how it will affect performance. Per the above, there will be a "slowdown".

I'd definitely recommend against that. You'd have to re-compile Wasm -> native for each contract after every start.

If you do it once per chain upgrade, that's safe enough. But at the end of the day that's a CosmWasm bug that will be fixed in 1.3 and beyond.

**Comment by DavidNix** [comment]
> > We could delete the cache on every restart, but I'm unsure how it will affect performance. Per the above, there will be a "slowdown".
> 
> I'd definitely recommend against that. You'd have to re-compile Wasm -> native for each contract after every start.
> 
> If you do it once per chain upgrade, that's safe enough. But at the end of the day that's a CosmWasm bug that will be fixed in 1.3 and beyond.

Thanks for the feedback @webmaster128. Can you point me to documentation or discussion that shows it will be fixed in 1.3 and beyond?

**Comment by webmaster128** [comment]
See https://github.com/CosmWasm/wasmvm/issues/426#issuecomment-1572711059

**Comment by DavidNix** [comment]
Great! If we decide to move forward with this feature, it will be opt-in and only if the pod is crashlooping. We won't automatically blow away the cache on every restart.

**Comment by DavidNix** [comment]
Rare edge case. Automation seems overkill, so closing.
