### ISSUE TITLE
idea: sync first, then worry about validator

### ISSUE THREAD

**Issue by danbryan** [strangelove-ventures/cosmos-operator#307]
Not sure what the current behavior is, but i think it would be nice if the workflow for new vals was, build the sentry, get it syncing, then worry about adding horcrux privval into the mix.  Is this currently supported by the operator, it will it wait for a connection to be established on :1234 before syncing chain data?

**Comment by DavidNix** [comment]
This could be more explicit, but you can change the `type: Sentry` to `type: ""` to revert to a fullnode. That removes looking for privval. Then revert back to `type: Sentry`.
