### ISSUE TITLE
The `haltHeight` on CosmosFullNode should accept 0 as a valid value

### ISSUE THREAD

**Issue by DavidNix** [strangelove-ventures/cosmos-operator#309]

**Comment by jonathanpberger** [comment]
Assigning to @danbryan as "good intro to `golang`".

**Comment by DavidNix** [comment]
Re-assigning. It won't be a great intro since the operator framework parses comments and creates code for you. [This story](https://github.com/strangelove-ventures/heighliner/issues/127), specifically allow setting cosmwasm version, would be a better intro.
