### ISSUE TITLE
Allow running Sentry nodes through the Operator

### ISSUE THREAD

**Issue by DavidNix** [strangelove-ventures/cosmos-operator#83]
My hypothesis is we extend CosmosFullNode with a `type` (or similar). Default is sentry node. 

Differences:
- Pruning (but that's up to the user unless we think there are reasonable defaults)
- P2P (need to confirm all sentries need external_address for p2p)
- Do not expose anything outside of p2p to the internet (but we don't do that anyway). Perhaps do not create the RPC service. 
- Privval port
- Privval services for internal ip addresses

**Comment by jackzampolin** [comment]
This is a big issue close @DavidNix 🙌
